services:
  - type: web
    name: vayubots
    env: python
    region: singapore                  # ✅ lowercase
    plan: starter                      # ✅ starter is fine unless you need >512MB RAM
    buildCommand: pip install --no-cache-dir -r requirements.prod.txt
    startCommand: uvicorn vayu.server.main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      # --- 🔐 Sensitive keys managed in Render Dashboard ---
      - key: OPENAI_API_KEY
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false

      # --- 🌎 Environment marker ---
      - key: ENV
        value: production

    autoDeploy: true
